
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Sujit Debnath", email = "sujit.debnath.bd@gmail.com"},
]
dependencies = [
    "numpy>=1.24.3",
    "opencv-python>=4.7.0.72",
    "pytest>=7.3.1",
]
requires-python = ">=3.9"
license = {text = "MIT"}
